name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Install python dependencies
      run: |
        python -m pip install -U pip
        pip install -r requirements-dev.txt
    - name: Run PyTest
      run: python -m pytest --durations=5 --cov-report=term --cov=mapi --numprocesses=2
